# Generated by Django 2.1.4 on 2018-12-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
